deepseek:
  models:
  - model: deepseek-chat
    parameters:
      frequency_penalty: 0
      max_tokens: 1024
      presence_penalty: 0
      system_message: You are an advanced AI assistant.
      temperature: 0.7
    version: v2
openai:
  models:
  - model: gpt-4o-mini
    parameters:
      frequency_penalty: 0
      max_tokens: 1024
      presence_penalty: 0
      system_message: You are a helpful assistant. You always start the output with
        "HELLO, I AM AI ASSITANT HS"
      temperature: 0.7
    version: default
  - model: gpt-4o-mini
    parameters:
      frequency_penalty: 0.5
      max_tokens: 1500
      presence_penalty: 0.1
      system_message: You are an advanced AI assistant
      temperature: 0.6
    version: v1
